<?php
/*
	  @name          news [controller]
	  @filename      news.c.php
	  @description   news controller class
	  Generated By Scaffolding Script
	  handels the following cases:
	  [add ]
	  [show]
	  [edit]
	  [rm  ]
	  @author   AlSayed Gamal <mail.gamal@gmail.com> <http://www.egamal.com>
*/
if(!isset($iWasThere)){
	  echo ("bang bang !");
}

Load()->control('control');

class home extends ctrl{
	function __construct($req) {
		parent::__construct($req);
		global $iWasThere;
		$this->req = $req;
		$this->name = 'home';

		#$this->html .= "<script>
		#				var LINK = '".LINK."';
		#	</script>";
		#$this->html .= "<script src='".LINK."/view/default/scripts/js.js'></script>";
		#$this->html .= "<script src='".LINK."/view/default/scripts/wysiwyg.js'></script>";

	}

	function _default() {
		// get last 5 items from media 
		// then show them
		Load()->model('media');
		$media = new media_model;

		$query = $media->select()->from('media')->limit(5)->sortType('DESC');

		$medias = $media->query($query->sql())->fetch();
		$mediaView = easy_render($this->name, 'media');

		if ($medias) {
			foreach ($medias as $media) {
				$mediaViewOut .= render_var($mediaView, $media);						
			}
		}
		
		// get last video;
		$arData['file'] = $medias[0]['file'];
		$video = render($this->name, 'video', $arData);
		
		$arData = array(
			'video'   => $video,
			'content' => $mediaViewOut
		);

		$this->html .= render($this->name, 'home', $arData);
	}
	
	function show() {
		Load()->model('media');
		$media = new media_model;

		$query = $media->select()->from('media')->limit(5)->sortType('DESC');

		$medias = $media->query($query->sql())->fetch();
		$mediaView = easy_render($this->name, 'media');

		if ($medias) {
			foreach ($medias as $media) {
				if ($media['id'] == $this->req['id']) {
					$file = $media['file'];
				}
					
				$mediaViewOut .= render_var($mediaView, $media);						
			}
		}

		$arData['file'] = $file;
		$video = render($this->name, 'video', $arData);
		
		$arData = array(
			'video'   => $video,
			'content' => $mediaViewOut
		);
		$this->html .= render($this->name, 'home', $arData);
	}
	
	function about() {
		$arData['content']=easy_render($this->name, 'about');
		$this->html .= render($this->name, 'home',$arData);
	}

	function contact() {
		$arData['content']=easy_render($this->name, 'contact');
		$this->html .= render($this->name, 'home',$arData);
	}

	function send() {
		include("shared/mailer.lib.php");
		$message="<pre>
				Message time: ".date('M d Js h:i:s')."
				Sender: {$this->req['senderMail']}
				Sender email: {$this->req['email']}
				Sender Message:
				".nl2br($this->req['msg'])."
			</pre>";
			
		ht_mail(WEB_ADMIN_MAIL,"Contact inquery",$message,'no-reply@scs-me.com',"contact-us form");
		$thankYou.=$this->goto(RUN_PATH,easy_render('.', 'thankyou'));
		$this->html .= render('.', 'home',array('content'=>$thankYou));
	}

	function footer() {
		return ($this->is_admin())? easy_render('.', 'footer') : easy_render('.', 'usrftr');
	}

}//EO home
?>
